# Init victoriametrics
---
- name: "Create {{ service_name }} user"
  user:
    name: "{{ user_name }}"
    uid: "{{ user_name_uid }}"
    comment: "{{ user_name_comment }}"
    state: "present"

- name: "Create {{ service_name }} data directory"
  file:
    path: "{{ host_data_dir }}"
    state: "directory"
    owner: "{{ user_name_uid }}"
    mode: "0775"

- name: "{{ service_name }} service config on host"
  template:
    src: "systemd/victoriametrics.service.j2"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    backup: yes
  notify: "{{ service_name }} restart"