#Remove victoriametrics service
---
- name: "Stop {{ service_name }}"
  service:
    name: "{{ service_name }}"
    enabled: no
    state: stopped
  ignore_errors: yes

- name: "Remove /etc/systemd/system/{{ service_name }}.service"
  file:
    path: "/etc/systemd/system/{{ service_name }}.service"
    state: absent
  notify: "{{ service_name }} restart uninstall"
